#!/bin/sh

# --------------------------------------------------------------------------- #
# Begin settings
# --------------------------------------------------------------------------- #

# SSH
SSH_ACCOUNT=accountname_sitename@ssh.phx.nearlyfreespeech.net

# HTTP authentication
# Define these to make the web display private.
# USERNAME=tlevine
# PASSWORD=chainsaws

# Filesystem, with trailing slashes
REPOSITORIES_DIR=/home/private/
PUBLIC_HTML_DIR=/home/public/
HTPASSWD_FILE=/home/protected/.htpasswd
BARELYWEBGIT_REPOSITORY=/home/private/barelywebgit/
TMP=/tmp

# --------------------------------------------------------------------------- #
# End settings
# --------------------------------------------------------------------------- #

set -e
cd $BARELYWEBGIT_REPOSITORY
. models

index() {
  # Retrieve repository list.
# repositories="`models_repositories \"$REPOSITORIES_DIR\"`"
  repositories="foo.git bar.git"

  # Make rows.
  echo > $TMP/_repository_rows.html
  for repository_full in ${repositories}
    do
    repository_partial="`echo $repository_full|sed s+^${REPOSITORIES_DIR}++`"
    sed "s+{{repository path}}+${repository_partial}+g" \
      web/_repository_row.html >> "${TMP}"/_repository_rows.html
  done

  # Add to the template.
  sed "/id=\"repositories\"/r ${TMP}/_repository_rows.html" \
    web/index.html > $TMP/public_html/index.html
  rm $TMP/_repository_rows.html

  # Other variables
  sed -i -e "s/{{SSH account}}/${SSH_ACCOUNT}/g" \
    $TMP/public_html/index.html
}

htpasswd() {

}

# Compilation directory
rm -Rf $TMP/public_html
cp -R web $TMP/public_html

# Dynamic stuff
index
# htpasswd

# Publish
cp -R $TMP/public_html $PUBLIC_HTML_DIR
