#!/bin/sh

# --------------------------------------------------------------------------- #
# Begin settings
# --------------------------------------------------------------------------- #

# HTTP authentication
# Define these to make the web display private.
# USERNAME=tlevine
# PASSWORD=chainsaws

# Filesystem
REPOSITORIES_DIR=/home/private
PUBLIC_HTML_DIR=/home/public
HTPASSWD_FILE=/home/protected/.htpasswd
BARELYWEBGIT_REPOSITORY=/home/private/barelywebgit
TMP=/tmp

# --------------------------------------------------------------------------- #
# End settings
# --------------------------------------------------------------------------- #

cd $BARELYWEBGIT_REPOSITORY
. models

index() {
  repositories=models_repositories "$REPOSITORIES_DIR"
  echo > /tmp/repository_rows.html
  for repository in repositories
    do
    sed "s/{{repository path}}/$repository/g" \
      templates/_repository_row.html >>  $TMP/_repository_rows.html
  done
}

htpasswd() {

}
