#!/bin/sh

# --------------------------------------------------------------------------- #
# Begin settings
# --------------------------------------------------------------------------- #

# SSH
SSH_ACCOUNT=accountname_sitename@ssh.phx.nearlyfreespeech.net

# HTTP authentication
# Define these to make the web display private.
# USERNAME=tlevine
# PASSWORD=chainsaws

# Filesystem, with trailing slashes
REPOSITORIES_DIR=/home/private/
PUBLIC_HTML_DIR=/home/public/
HTPASSWD_FILE=/home/protected/.htpasswd
BARELYWEBGIT_REPOSITORY=/home/private/barelywebgit/
TMP=/tmp

# --------------------------------------------------------------------------- #
# End settings
# --------------------------------------------------------------------------- #

set -e
cd $BARELYWEBGIT_REPOSITORY

repositories="`find $REPOSITORIES_DIR -name *.git`"

index() {
  # Make rows.
  echo > $TMP/_repository_rows.html
  for repository_full in ${repositories}
    do
    repository_partial="`echo $repository_full|sed s&^${REPOSITORIES_DIR}&&`"
    sed -e "s&{{repository path}}&${repository_partial}&g" \
      -e "s/{{SSH account}}/${SSH_ACCOUNT}/g" \
      web/_repository_row.html >> "${TMP}"/_repository_rows.html
  done

  # Add to the template.
  sed "/id=\"repositories\"/r ${TMP}/_repository_rows.html" \
    web/index.html > $TMP/public_html/index.html
  rm $TMP/_repository_rows.html
}

htpasswd() {

}

# Compilation directory
rm -Rf $TMP/public_html
cp -R web $TMP/public_html

# Dynamic stuff
index
# htpasswd

# Publish
rm -Rf $PUBLIC_HTML_DIR/*
cp -R $TMP/public_html/* $PUBLIC_HTML_DIR
